export const ADD_FAVOURITE = 'FAVOURITE/ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const FETCH_CATS = 'CATS/FETCH_CATS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const GET_LIKE = 'APP/GET_LIKE';
export const REMOVE_LIKE = 'APP/REMOVE_LIKE';

